### ISSUE TITLE
HOWTO: shared attributes

### ISSUE THREAD

**Issue by ineu** [sorah/hocho#12]
I have an itamae project configuring a set of similar machines. They share some attributes, so I'm using two yml files per host: one shared and one unique.

Now I'm trying to migrate to hocho. The problem I'm having is:
1. Hocho doesn't support --node-json or --node-yaml switches
2. Hocho (or rather Psych) doesn't parse yaml aliases, which doesn't allow moving shared attributes in a separate key to reuse for specific hosts

Is there some workaround for this issue? If no, I can create a pull request adding support for --node-yaml.

**Comment by sorah** [comment]
File inventory provider is not designed to load such attributes in DRY way. The current recommendation is to use [ruby_script property provider](https://github.com/sorah/hocho/blob/master/lib/hocho/property_providers/ruby_script.rb) (or write your own {inventory,property} provider) to populate shared values.

Or, you can popuate such values at (m)itamae level by adding a shared recipe file that populate node attribute into run_list.

**Comment by ineu** [comment]
Ok, this seems to work in both itamae and mitamae:
```ruby
node.reverse_merge!(YAML.load(File.read("vars/nodes.yml")))
node.reverse_merge!(YAML.load(File.read("vars/node-1.yml")))

include_recipe "_nodes.rb"
```
Thank you!

**Comment by sorah** [comment]
if it doesn't need conditions, then I believe you can use default property provider

**Comment by ineu** [comment]
Not sure I understand how to do it. From the docs I though that `attributes` in the hosts file is the only possible way. Is it not?
